### PR TITLE
Solves startup-script issue and APIError call on nil error

### LINKED ISSUE #10: GCP Provider error startup-script: Must not run with sudo
Hello, running into an error trying to spin up a linux runner in GCP using the garm_provider_gcp.

```
Feb 29 16:12:57 debian google_metadata_script_runner[903]: startup-script: Must not run with sudo
Feb 29 16:13:02 debian google_metadata_script_runner[903]: startup-script: Must not run with sudo
```

Any idea of what I am doing wrong? 

I was thinking of some workarounds: 
1. I can add `export RUNNER_ALLOW_RUNASROOT="1"` as outlined on https://serverfault.com/questions/1052695/must-not-run-with-sudo-while-trying-to-create-a-runner-using-github-actions but this is not ideal.
2. Switch to runner user `sudo su runner` in the additionalCommands section of the ComposeUserData at https://github.com/cloudbase/garm-provider-gcp/blob/main/internal/spec/spec.go#L215. 

Some details (ill update this if I think of any additional details):
- I am using a snapshot created from `projects/debian-cloud/global/images/family/debian-11`

### PR DESCRIPTION
**Pull request by fabi200123**
Solves:
- `err.(*apierror.APIError).HTTPCode()` call on `nil` error
- startup-script not properly switching user

Fixes #10

### CODE REVIEW

File: internal/spec/spec.go [hunk 1]
```diff
@@ -202,22 +203,23 @@ func (r RunnerSpec) ComposeUserData() (string, error) {
...
+			// Create the runner home directory if it doesn't exist
+			"sudo mkdir -p /home/" + defaults.DefaultUser,
+			// Add user to sudoers
+			"sudo usermod -aG sudo " + defaults.DefaultUser,
+			// Check curl and tar are installed
+			"sudo apt-get update && sudo apt-get install -y curl tar",
+			// Install the runner
+			"echo " + asBase64 + " | base64 -d > /install_runner.sh",
+			"chmod +x /install_runner.sh",
+			"echo '" + defaults.DefaultUser + " ALL=(ALL) NOPASSWD:ALL' | sudo EDITOR='tee -a' visudo",
```
Comment (gabriel-samfira) [inline internal/spec/spec.go:218]: no need for `visudo` here. Just write the file with the proper permissions. The `visudo` command is just meant to validate the `sudoers` file. If you're certain that the string is valid, you can just `echo`.

Comment (gabriel-samfira) [reply internal/spec/spec.go:218]: also, most systems have a `/etc/sudoers.d/` folder. So you can just echo:

```bash
echo 'runner  ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/garm
```

Comment (fabi200123) [reply internal/spec/spec.go]: Updated! Thanks!
